version: '2'
services:
 iotagentul:
  build: .
  environment:
   - NODEJS_VERSION=0.10.46
  ports:
   - "7896:7896"
   - "4041:4041"
  links:
   - mongo
  restart: always
  volumes:
   - "./config-blank.js:/opt/iotaul/config-blank.js"
 mongo:
  image: mongo:3.2
  volumes:
   - "./db/mongo/:/data/db"
  command: --nojournal
